*&---------------------------------------------------------------------*
*& Include zzbvag_survey_adt_05_2025_top
*&---------------------------------------------------------------------*

DATA event TYPE char30.

TABLES sscrfields.

"Question 1
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE title_1.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q1_1.
    PARAMETERS: pq1_1 RADIOBUTTON GROUP rad1 DEFAULT 'X' USER-COMMAND q1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q1_2.
    PARAMETERS: pq1_2 RADIOBUTTON GROUP rad1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q1_3.
    PARAMETERS: pq1_3 RADIOBUTTON GROUP rad1.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q1_4.
    PARAMETERS: pq1_4 RADIOBUTTON GROUP rad1.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: othr_1 TYPE char255 LOWER CASE MODIF ID q1.

  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN PUSHBUTTON 5(30) but1 USER-COMMAND usrc1 VISIBLE LENGTH 30.
SELECTION-SCREEN END OF BLOCK b1.


"Question 2
SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE title_2.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q2_1.
    PARAMETERS: pq2_1 RADIOBUTTON GROUP rad2 DEFAULT 'X' USER-COMMAND q2.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q2_2.
    PARAMETERS: pq2_2 RADIOBUTTON GROUP rad2.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q2_3.
    PARAMETERS: pq2_3 RADIOBUTTON GROUP rad2.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q2_4.
    PARAMETERS: pq2_4 RADIOBUTTON GROUP rad2.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: othr_2 TYPE char255 LOWER CASE MODIF ID q2.
  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN PUSHBUTTON 5(30) but2 USER-COMMAND usrc2 VISIBLE LENGTH 30.
SELECTION-SCREEN END OF BLOCK b2.


"Question 3
SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE title_3.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q3_1.
    PARAMETERS: pq3_1 RADIOBUTTON GROUP rad3 DEFAULT 'X' USER-COMMAND q3.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q3_2.
    PARAMETERS: pq3_2 RADIOBUTTON GROUP rad3.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q3_3.
    PARAMETERS: pq3_3 RADIOBUTTON GROUP rad3.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q3_4.
    PARAMETERS: pq3_4 RADIOBUTTON GROUP rad3.
  SELECTION-SCREEN END OF LINE.
  PARAMETERS: othr_3 TYPE char255 LOWER CASE MODIF ID q3.

  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN PUSHBUTTON 5(30) but3 USER-COMMAND usrc3 VISIBLE LENGTH 30.
SELECTION-SCREEN END OF BLOCK b3.


"Question 4
SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE title_4.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q4_1.
    PARAMETERS: pq4_1 RADIOBUTTON GROUP rad4 DEFAULT 'X' USER-COMMAND q4.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q4_2.
    PARAMETERS: pq4_2 RADIOBUTTON GROUP rad4.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q4_3.
    PARAMETERS: pq4_3 RADIOBUTTON GROUP rad4.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 2.
    SELECTION-SCREEN COMMENT 1(70) ans_q4_4.
    PARAMETERS: pq4_4 RADIOBUTTON GROUP rad4.
  SELECTION-SCREEN END OF LINE.

  PARAMETERS: othr_4 TYPE char255 LOWER CASE MODIF ID q4.
  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN PUSHBUTTON 5(30) but4 USER-COMMAND usrc4 VISIBLE LENGTH 30.

SELECTION-SCREEN END OF BLOCK b4.
